[project]
name = "start-cloudflare"
version = "0.0.8"
description = "A Pydantic BaseSettings class intended to be extended by other Cloudflare services."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
  "python-dotenv >= 1.0",
  "pydantic-settings",
  "pydantic",
  "email-validator >= 2.3.0"
]

[dependency-groups]
dev = [
  "rich >= 15.0",
  # testing
  "pytest >= 9.0",
  "pytest-cov >= 7.0",
  # docs
  "zensical>=0.0.39",
  "mkdocstrings-python>=2.0.3",
]

[tool.pytest.ini_options]
minversion = "8.4"
addopts = "-ra -q --cov --doctest-modules"
testpaths = ["tests", "start_cloudflare"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["F401", "F403"]
fixable = ["F", "E", "W", "I001"]
select = ["F", "E", "W", "I001"]
