name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  uv-example:
    name: Python (UV)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.22"

      - name: Install the project with UV
        run: uv sync --locked --all-extras --dev

      - name: Install Dependencies
        run: |
          uv tool install pre-commit --with pre-commit-uv
          pre-commit install-hooks

      - name: Lint with pre-commit
        run: pre-commit run --all-files

      - name: Install project in editable mode prior to tests
        run: uv run pip install -e .

      - name: Run tests
        run: uv run pytest
